//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Adminstration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Adminstration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Adminstration", typeof(Adminstration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch.
        /// </summary>
        public static string BranchCreate {
            get {
                return ResourceManager.GetString("BranchCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Details.
        /// </summary>
        public static string BranchDetails {
            get {
                return ResourceManager.GetString("BranchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Branch.
        /// </summary>
        public static string BranchEdit {
            get {
                return ResourceManager.GetString("BranchEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code.
        /// </summary>
        public static string BranchId {
            get {
                return ResourceManager.GetString("BranchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch(Ar).
        /// </summary>
        public static string BranchNameAr {
            get {
                return ResourceManager.GetString("BranchNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string BranchNameEn {
            get {
                return ResourceManager.GetString("BranchNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Branch.
        /// </summary>
        public static string BranchNew {
            get {
                return ResourceManager.GetString("BranchNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string BranchTitle {
            get {
                return ResourceManager.GetString("BranchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date.
        /// </summary>
        public static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string CurrentCost {
            get {
                return ResourceManager.GetString("CurrentCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Contract.
        /// </summary>
        public static string SIMCardContract {
            get {
                return ResourceManager.GetString("SIMCardContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SIM Card Contract.
        /// </summary>
        public static string SIMCardContractCreate {
            get {
                return ResourceManager.GetString("SIMCardContractCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Contract Details.
        /// </summary>
        public static string SIMCardContractDetails {
            get {
                return ResourceManager.GetString("SIMCardContractDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SIM Card Contract.
        /// </summary>
        public static string SIMCardContractEdit {
            get {
                return ResourceManager.GetString("SIMCardContractEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Code.
        /// </summary>
        public static string SIMCardContractId {
            get {
                return ResourceManager.GetString("SIMCardContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SIM Card Contract.
        /// </summary>
        public static string SIMCardContractNew {
            get {
                return ResourceManager.GetString("SIMCardContractNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract No.
        /// </summary>
        public static string SIMCardContractNo {
            get {
                return ResourceManager.GetString("SIMCardContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string SIMCardContractProvider {
            get {
                return ResourceManager.GetString("SIMCardContractProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Provider.
        /// </summary>
        public static string SIMCardProvider {
            get {
                return ResourceManager.GetString("SIMCardProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Provider.
        /// </summary>
        public static string SIMCardProviderCreate {
            get {
                return ResourceManager.GetString("SIMCardProviderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Details.
        /// </summary>
        public static string SIMCardProviderDetails {
            get {
                return ResourceManager.GetString("SIMCardProviderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Provider.
        /// </summary>
        public static string SIMCardProviderEdit {
            get {
                return ResourceManager.GetString("SIMCardProviderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Code.
        /// </summary>
        public static string SIMCardProviderId {
            get {
                return ResourceManager.GetString("SIMCardProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name(Ar).
        /// </summary>
        public static string SIMCardProviderNameAr {
            get {
                return ResourceManager.GetString("SIMCardProviderNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        public static string SIMCardProviderNameEn {
            get {
                return ResourceManager.GetString("SIMCardProviderNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Provider.
        /// </summary>
        public static string SIMCardProviderNew {
            get {
                return ResourceManager.GetString("SIMCardProviderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique Company.
        /// </summary>
        public static string TechniqueCompany {
            get {
                return ResourceManager.GetString("TechniqueCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Technique Company.
        /// </summary>
        public static string TechniqueCompanyCreate {
            get {
                return ResourceManager.GetString("TechniqueCompanyCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique Company Details.
        /// </summary>
        public static string TechniqueCompanyDetails {
            get {
                return ResourceManager.GetString("TechniqueCompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Technique Company.
        /// </summary>
        public static string TechniqueCompanyEdit {
            get {
                return ResourceManager.GetString("TechniqueCompanyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string TechniqueCompanyName {
            get {
                return ResourceManager.GetString("TechniqueCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Technique Company.
        /// </summary>
        public static string TechniqueCompanyNew {
            get {
                return ResourceManager.GetString("TechniqueCompanyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique System.
        /// </summary>
        public static string TechniqueSystem {
            get {
                return ResourceManager.GetString("TechniqueSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Technique System.
        /// </summary>
        public static string TechniqueSystemCreate {
            get {
                return ResourceManager.GetString("TechniqueSystemCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique Details.
        /// </summary>
        public static string TechniqueSystemDetails {
            get {
                return ResourceManager.GetString("TechniqueSystemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Technique System.
        /// </summary>
        public static string TechniqueSystemEdit {
            get {
                return ResourceManager.GetString("TechniqueSystemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Technique System.
        /// </summary>
        public static string TechniqueSystemNew {
            get {
                return ResourceManager.GetString("TechniqueSystemNew", resourceCulture);
            }
        }
    }
}
