//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sales() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Sales", typeof(Sales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Contact Name.
        /// </summary>
        public static string AltContactName {
            get {
                return ResourceManager.GetString("AltContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Contact Telephone.
        /// </summary>
        public static string AltContactTelephone {
            get {
                return ResourceManager.GetString("AltContactTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Contact Name.
        /// </summary>
        public static string AlternativeContactName {
            get {
                return ResourceManager.GetString("AlternativeContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Contact Telephone.
        /// </summary>
        public static string AlternativeContactTelephone {
            get {
                return ResourceManager.GetString("AlternativeContactTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Request has been Approved.
        /// </summary>
        public static string ApprovedDeliveryRequestNotificationContent {
            get {
                return ResourceManager.GetString("ApprovedDeliveryRequestNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Delivery Request.
        /// </summary>
        public static string ApprovedDeliveryRequestNotificationTitle {
            get {
                return ResourceManager.GetString("ApprovedDeliveryRequestNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Contact.
        /// </summary>
        public static string CustomerContact {
            get {
                return ResourceManager.GetString("CustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your delivery request for customer(@customer) transfer to delivery phase.
        /// </summary>
        public static string DeliveryRequestInDeliveryPhaseNotificationContent {
            get {
                return ResourceManager.GetString("DeliveryRequestInDeliveryPhaseNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery request transfer to delivery phase.
        /// </summary>
        public static string DeliveryRequestInDeliveryPhaseNotificationTitle {
            get {
                return ResourceManager.GetString("DeliveryRequestInDeliveryPhaseNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of sales.
        /// </summary>
        public static string POS {
            get {
                return ResourceManager.GetString("POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Employee.
        /// </summary>
        public static string SalesEmployee {
            get {
                return ResourceManager.GetString("SalesEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string SaleTransactionType {
            get {
                return ResourceManager.GetString("SaleTransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Request has been assigned to technicians.
        /// </summary>
        public static string TechnicianAssignedDeliveryRequestNotificationContent {
            get {
                return ResourceManager.GetString("TechnicianAssignedDeliveryRequestNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Request Tech. Assigned.
        /// </summary>
        public static string TechnicianAssignedDeliveryRequestNotificationTitle {
            get {
                return ResourceManager.GetString("TechnicianAssignedDeliveryRequestNotificationTitle", resourceCulture);
            }
        }
    }
}
