//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Security {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Security() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Security", typeof(Security).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions(En).
        /// </summary>
        public static string ServiceActionsEn {
            get {
                return ResourceManager.GetString("ServiceActionsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name(En).
        /// </summary>
        public static string ServiceNameEn {
            get {
                return ResourceManager.GetString("ServiceNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Role.
        /// </summary>
        public static string SystemRole {
            get {
                return ResourceManager.GetString("SystemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create System Role.
        /// </summary>
        public static string SystemRoleCreate {
            get {
                return ResourceManager.GetString("SystemRoleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Role Details.
        /// </summary>
        public static string SystemRoleDetails {
            get {
                return ResourceManager.GetString("SystemRoleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit System Role.
        /// </summary>
        public static string SystemRoleEdit {
            get {
                return ResourceManager.GetString("SystemRoleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Role Name(Ar).
        /// </summary>
        public static string SystemRoleNameAr {
            get {
                return ResourceManager.GetString("SystemRoleNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Role Name(En).
        /// </summary>
        public static string SystemRoleNameEn {
            get {
                return ResourceManager.GetString("SystemRoleNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New System Role.
        /// </summary>
        public static string SystemRoleNew {
            get {
                return ResourceManager.GetString("SystemRoleNew", resourceCulture);
            }
        }
    }
}
