//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServerManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ServerManagement", typeof(ServerManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brand.
        /// </summary>
        public static string BrandCreate {
            get {
                return ResourceManager.GetString("BrandCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Details.
        /// </summary>
        public static string BrandDetails {
            get {
                return ResourceManager.GetString("BrandDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Brand.
        /// </summary>
        public static string BrandEdit {
            get {
                return ResourceManager.GetString("BrandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Name.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brand.
        /// </summary>
        public static string BrandNew {
            get {
                return ResourceManager.GetString("BrandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Server Port.
        /// </summary>
        public static string BrandServerPort {
            get {
                return ResourceManager.GetString("BrandServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brand Server Port.
        /// </summary>
        public static string BrandServerPortCreate {
            get {
                return ResourceManager.GetString("BrandServerPortCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Server Port Details.
        /// </summary>
        public static string BrandServerPortDetails {
            get {
                return ResourceManager.GetString("BrandServerPortDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Brand Server Port.
        /// </summary>
        public static string BrandServerPortEdit {
            get {
                return ResourceManager.GetString("BrandServerPortEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brand Server Port.
        /// </summary>
        public static string BrandServerPortNew {
            get {
                return ResourceManager.GetString("BrandServerPortNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Name.
        /// </summary>
        public static string ProtocolName {
            get {
                return ResourceManager.GetString("ProtocolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string ServerIP {
            get {
                return ResourceManager.GetString("ServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string SystemServerIP {
            get {
                return ResourceManager.GetString("SystemServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Server IP.
        /// </summary>
        public static string SystemServerIPCreate {
            get {
                return ResourceManager.GetString("SystemServerIPCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP Details.
        /// </summary>
        public static string SystemServerIPDetails {
            get {
                return ResourceManager.GetString("SystemServerIPDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Server IP.
        /// </summary>
        public static string SystemServerIPEdit {
            get {
                return ResourceManager.GetString("SystemServerIPEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Server IP.
        /// </summary>
        public static string SystemServerIPNew {
            get {
                return ResourceManager.GetString("SystemServerIPNew", resourceCulture);
            }
        }
    }
}
