//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServerManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ServerManagement", typeof(ServerManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative GSM Prefix.
        /// </summary>
        public static string AltGSMPrefix {
            get {
                return ResourceManager.GetString("AltGSMPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brand.
        /// </summary>
        public static string BrandCreate {
            get {
                return ResourceManager.GetString("BrandCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Details.
        /// </summary>
        public static string BrandDetails {
            get {
                return ResourceManager.GetString("BrandDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Brand.
        /// </summary>
        public static string BrandEdit {
            get {
                return ResourceManager.GetString("BrandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Name.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brand.
        /// </summary>
        public static string BrandNew {
            get {
                return ResourceManager.GetString("BrandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Server Port.
        /// </summary>
        public static string BrandServerPort {
            get {
                return ResourceManager.GetString("BrandServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brand Server Port.
        /// </summary>
        public static string BrandServerPortCreate {
            get {
                return ResourceManager.GetString("BrandServerPortCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Server Port Details.
        /// </summary>
        public static string BrandServerPortDetails {
            get {
                return ResourceManager.GetString("BrandServerPortDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Brand Server Port.
        /// </summary>
        public static string BrandServerPortEdit {
            get {
                return ResourceManager.GetString("BrandServerPortEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brand Server Port.
        /// </summary>
        public static string BrandServerPortNew {
            get {
                return ResourceManager.GetString("BrandServerPortNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract No.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM Prefix.
        /// </summary>
        public static string GSMPrefix {
            get {
                return ResourceManager.GetString("GSMPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Name.
        /// </summary>
        public static string ProtocolName {
            get {
                return ResourceManager.GetString("ProtocolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string ServerIP {
            get {
                return ResourceManager.GetString("ServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt GSM.
        /// </summary>
        public static string SIMCardAltGSM {
            get {
                return ResourceManager.GetString("SIMCardAltGSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company S/N.
        /// </summary>
        public static string SIMCardCompanySerialNumber {
            get {
                return ResourceManager.GetString("SIMCardCompanySerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string SIMCardContract {
            get {
                return ResourceManager.GetString("SIMCardContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SIM Card.
        /// </summary>
        public static string SIMCardCreate {
            get {
                return ResourceManager.GetString("SIMCardCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string SIMCardCreateDate {
            get {
                return ResourceManager.GetString("SIMCardCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Details.
        /// </summary>
        public static string SIMCardDetails {
            get {
                return ResourceManager.GetString("SIMCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SIM Card.
        /// </summary>
        public static string SIMCardEdit {
            get {
                return ResourceManager.GetString("SIMCardEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM.
        /// </summary>
        public static string SIMCardGSM {
            get {
                return ResourceManager.GetString("SIMCardGSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SIM Card.
        /// </summary>
        public static string SIMCardNew {
            get {
                return ResourceManager.GetString("SIMCardNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        public static string SIMCardPurchaseDate {
            get {
                return ResourceManager.GetString("SIMCardPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Cards.
        /// </summary>
        public static string SIMCards {
            get {
                return ResourceManager.GetString("SIMCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SIMCardSerialNumber {
            get {
                return ResourceManager.GetString("SIMCardSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Status.
        /// </summary>
        public static string SIMCardStatus {
            get {
                return ResourceManager.GetString("SIMCardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Status Details.
        /// </summary>
        public static string SIMCardStatusDetails {
            get {
                return ResourceManager.GetString("SIMCardStatusDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SIM Card Status.
        /// </summary>
        public static string SIMCardStatusEdit {
            get {
                return ResourceManager.GetString("SIMCardStatusEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status(Ar).
        /// </summary>
        public static string SIMCardStatusNameAr {
            get {
                return ResourceManager.GetString("SIMCardStatusNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SIMCardStatusNameEn {
            get {
                return ResourceManager.GetString("SIMCardStatusNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Status.
        /// </summary>
        public static string SIMCardStatusTitle {
            get {
                return ResourceManager.GetString("SIMCardStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card.
        /// </summary>
        public static string SIMCardTitle {
            get {
                return ResourceManager.GetString("SIMCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string SystemServerIP {
            get {
                return ResourceManager.GetString("SystemServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Server IP.
        /// </summary>
        public static string SystemServerIPCreate {
            get {
                return ResourceManager.GetString("SystemServerIPCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP Details.
        /// </summary>
        public static string SystemServerIPDetails {
            get {
                return ResourceManager.GetString("SystemServerIPDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Server IP.
        /// </summary>
        public static string SystemServerIPEdit {
            get {
                return ResourceManager.GetString("SystemServerIPEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Server IP.
        /// </summary>
        public static string SystemServerIPNew {
            get {
                return ResourceManager.GetString("SystemServerIPNew", resourceCulture);
            }
        }
    }
}
