//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServerManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ServerManagement", typeof(ServerManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Id.
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Status.
        /// </summary>
        public static string AccountStatus {
            get {
                return ResourceManager.GetString("AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account User Name.
        /// </summary>
        public static string AccountUserName {
            get {
                return ResourceManager.GetString("AccountUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ser.Add.
        /// </summary>
        public static string AddToServer {
            get {
                return ResourceManager.GetString("AddToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative GSM Prefix.
        /// </summary>
        public static string AltGSMPrefix {
            get {
                return ResourceManager.GetString("AltGSMPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brand.
        /// </summary>
        public static string BrandCreate {
            get {
                return ResourceManager.GetString("BrandCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Details.
        /// </summary>
        public static string BrandDetails {
            get {
                return ResourceManager.GetString("BrandDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Brand.
        /// </summary>
        public static string BrandEdit {
            get {
                return ResourceManager.GetString("BrandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Name.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brand.
        /// </summary>
        public static string BrandNew {
            get {
                return ResourceManager.GetString("BrandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Server Port.
        /// </summary>
        public static string BrandServerPort {
            get {
                return ResourceManager.GetString("BrandServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brand Server Port.
        /// </summary>
        public static string BrandServerPortCreate {
            get {
                return ResourceManager.GetString("BrandServerPortCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Server Port Details.
        /// </summary>
        public static string BrandServerPortDetails {
            get {
                return ResourceManager.GetString("BrandServerPortDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Brand Server Port.
        /// </summary>
        public static string BrandServerPortEdit {
            get {
                return ResourceManager.GetString("BrandServerPortEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brand Server Port.
        /// </summary>
        public static string BrandServerPortNew {
            get {
                return ResourceManager.GetString("BrandServerPortNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to server.
        /// </summary>
        public static string ButtonDeliveryDeviceServerAdd {
            get {
                return ResourceManager.GetString("ButtonDeliveryDeviceServerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client id.
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Status.
        /// </summary>
        public static string ClientStatus {
            get {
                return ResourceManager.GetString("ClientStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Namr(Ar).
        /// </summary>
        public static string ContactNameAr {
            get {
                return ResourceManager.GetString("ContactNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name(En).
        /// </summary>
        public static string ContactNameEn {
            get {
                return ResourceManager.GetString("ContactNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract No.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        public static string CreateCustomer {
            get {
                return ResourceManager.GetString("CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer Contact.
        /// </summary>
        public static string CreateCustomerContact {
            get {
                return ResourceManager.GetString("CreateCustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position(Ar).
        /// </summary>
        public static string CustomerContactPositionAr {
            get {
                return ResourceManager.GetString("CustomerContactPositionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position(En).
        /// </summary>
        public static string CustomerContactPositionEn {
            get {
                return ResourceManager.GetString("CustomerContactPositionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Dolphin Id.
        /// </summary>
        public static string CustomerDolphinId {
            get {
                return ResourceManager.GetString("CustomerDolphinId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id.
        /// </summary>
        public static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name (Ar).
        /// </summary>
        public static string CustomerNameAr {
            get {
                return ResourceManager.GetString("CustomerNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name (En).
        /// </summary>
        public static string CustomerNameEn {
            get {
                return ResourceManager.GetString("CustomerNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Server Account.
        /// </summary>
        public static string CustomerServerAccount {
            get {
                return ResourceManager.GetString("CustomerServerAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Server Units.
        /// </summary>
        public static string CustomerServerUnits {
            get {
                return ResourceManager.GetString("CustomerServerUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Server Units Details.
        /// </summary>
        public static string CustomerServerUnitsDetails {
            get {
                return ResourceManager.GetString("CustomerServerUnitsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Count (Deleted).
        /// </summary>
        public static string DeletedUnitsCount {
            get {
                return ResourceManager.GetString("DeletedUnitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery devices added to server successfully.
        /// </summary>
        public static string DeliveryDeviceAddedToServerSuccessMessage {
            get {
                return ResourceManager.GetString("DeliveryDeviceAddedToServerSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryDeviceAddToServer.
        /// </summary>
        public static string DeliveryDeviceServerAdd {
            get {
                return ResourceManager.GetString("DeliveryDeviceServerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Configuration.
        /// </summary>
        public static string DeviceConfiguration {
            get {
                return ResourceManager.GetString("DeviceConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Device.
        /// </summary>
        public static string DeviceConfigurationCreate {
            get {
                return ResourceManager.GetString("DeviceConfigurationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Configuration.
        /// </summary>
        public static string DeviceConfigurationNew {
            get {
                return ResourceManager.GetString("DeviceConfigurationNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Server Name.
        /// </summary>
        public static string DeviceServerName {
            get {
                return ResourceManager.GetString("DeviceServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM Prefix.
        /// </summary>
        public static string GSMPrefix {
            get {
                return ResourceManager.GetString("GSMPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Connection.
        /// </summary>
        public static string LastConnection {
            get {
                return ResourceManager.GetString("LastConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        public static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer Contact.
        /// </summary>
        public static string NewCustomerContact {
            get {
                return ResourceManager.GetString("NewCustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Delivery Note has been added.
        /// </summary>
        public static string NewDeliveryNoteNotificationContent {
            get {
                return ResourceManager.GetString("NewDeliveryNoteNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Delivery Note.
        /// </summary>
        public static string NewDeliveryNoteNotificationTitle {
            get {
                return ResourceManager.GetString("NewDeliveryNoteNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Name.
        /// </summary>
        public static string ProtocolName {
            get {
                return ResourceManager.GetString("ProtocolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Customer Name.
        /// </summary>
        public static string ServerCustomerName {
            get {
                return ResourceManager.GetString("ServerCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string ServerIP {
            get {
                return ResourceManager.GetString("ServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerUnit.
        /// </summary>
        public static string ServerUnit {
            get {
                return ResourceManager.GetString("ServerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ser.Updated.
        /// </summary>
        public static string ServerUpdated {
            get {
                return ResourceManager.GetString("ServerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt GSM.
        /// </summary>
        public static string SIMCardAltGSM {
            get {
                return ResourceManager.GetString("SIMCardAltGSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider S/N.
        /// </summary>
        public static string SIMCardCompanySerialNumber {
            get {
                return ResourceManager.GetString("SIMCardCompanySerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string SIMCardContract {
            get {
                return ResourceManager.GetString("SIMCardContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SIM Card.
        /// </summary>
        public static string SIMCardCreate {
            get {
                return ResourceManager.GetString("SIMCardCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string SIMCardCreateDate {
            get {
                return ResourceManager.GetString("SIMCardCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Details.
        /// </summary>
        public static string SIMCardDetails {
            get {
                return ResourceManager.GetString("SIMCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SIM Card.
        /// </summary>
        public static string SIMCardEdit {
            get {
                return ResourceManager.GetString("SIMCardEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM.
        /// </summary>
        public static string SIMCardGSM {
            get {
                return ResourceManager.GetString("SIMCardGSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SIM Card.
        /// </summary>
        public static string SIMCardNew {
            get {
                return ResourceManager.GetString("SIMCardNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        public static string SIMCardPurchaseDate {
            get {
                return ResourceManager.GetString("SIMCardPurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Cards.
        /// </summary>
        public static string SIMCards {
            get {
                return ResourceManager.GetString("SIMCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SIMCardSerialNumber {
            get {
                return ResourceManager.GetString("SIMCardSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Status.
        /// </summary>
        public static string SIMCardStatus {
            get {
                return ResourceManager.GetString("SIMCardStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Status Details.
        /// </summary>
        public static string SIMCardStatusDetails {
            get {
                return ResourceManager.GetString("SIMCardStatusDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SIM Card Status.
        /// </summary>
        public static string SIMCardStatusEdit {
            get {
                return ResourceManager.GetString("SIMCardStatusEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status(Ar).
        /// </summary>
        public static string SIMCardStatusNameAr {
            get {
                return ResourceManager.GetString("SIMCardStatusNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SIMCardStatusNameEn {
            get {
                return ResourceManager.GetString("SIMCardStatusNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Status.
        /// </summary>
        public static string SIMCardStatusTitle {
            get {
                return ResourceManager.GetString("SIMCardStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card.
        /// </summary>
        public static string SIMCardTitle {
            get {
                return ResourceManager.GetString("SIMCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string SystemServerIP {
            get {
                return ResourceManager.GetString("SystemServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Server IP.
        /// </summary>
        public static string SystemServerIPCreate {
            get {
                return ResourceManager.GetString("SystemServerIPCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP Details.
        /// </summary>
        public static string SystemServerIPDetails {
            get {
                return ResourceManager.GetString("SystemServerIPDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Server IP.
        /// </summary>
        public static string SystemServerIPEdit {
            get {
                return ResourceManager.GetString("SystemServerIPEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Server IP.
        /// </summary>
        public static string SystemServerIPNew {
            get {
                return ResourceManager.GetString("SystemServerIPNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Count (Total).
        /// </summary>
        public static string TotalUnitsCount {
            get {
                return ResourceManager.GetString("TotalUnitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech.Track.
        /// </summary>
        public static string TrackWithTechnician {
            get {
                return ResourceManager.GetString("TrackWithTechnician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Id.
        /// </summary>
        public static string UnitId {
            get {
                return ResourceManager.GetString("UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units Count (Working).
        /// </summary>
        public static string WorkingUnitsCount {
            get {
                return ResourceManager.GetString("WorkingUnitsCount", resourceCulture);
            }
        }
    }
}
