//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Store {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Store() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Store", typeof(Store).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Device.
        /// </summary>
        public static string DeviceCreate {
            get {
                return ResourceManager.GetString("DeviceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string DeviceCreateDate {
            get {
                return ResourceManager.GetString("DeviceCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Details.
        /// </summary>
        public static string DeviceDetails {
            get {
                return ResourceManager.GetString("DeviceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Card.
        /// </summary>
        public static string DeviceEdit {
            get {
                return ResourceManager.GetString("DeviceEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI.
        /// </summary>
        public static string DeviceIMEI {
            get {
                return ResourceManager.GetString("DeviceIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type.
        /// </summary>
        public static string DeviceModelType {
            get {
                return ResourceManager.GetString("DeviceModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type.
        /// </summary>
        public static string DeviceModelTypeName {
            get {
                return ResourceManager.GetString("DeviceModelTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device.
        /// </summary>
        public static string DeviceNew {
            get {
                return ResourceManager.GetString("DeviceNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string DeviceSerialNumber {
            get {
                return ResourceManager.GetString("DeviceSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DeviceStatusNameEn {
            get {
                return ResourceManager.GetString("DeviceStatusNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string DeviceTitle {
            get {
                return ResourceManager.GetString("DeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string Firmware {
            get {
                return ResourceManager.GetString("Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SIM Card.
        /// </summary>
        public static string SIMCardCreate {
            get {
                return ResourceManager.GetString("SIMCardCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string SIMCardCreateDate {
            get {
                return ResourceManager.GetString("SIMCardCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card Details.
        /// </summary>
        public static string SIMCardDetails {
            get {
                return ResourceManager.GetString("SIMCardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit SIM Card.
        /// </summary>
        public static string SIMCardEdit {
            get {
                return ResourceManager.GetString("SIMCardEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM.
        /// </summary>
        public static string SIMCardGSM {
            get {
                return ResourceManager.GetString("SIMCardGSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SIM Card.
        /// </summary>
        public static string SIMCardNew {
            get {
                return ResourceManager.GetString("SIMCardNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Cards.
        /// </summary>
        public static string SIMCards {
            get {
                return ResourceManager.GetString("SIMCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SIMCardSerialNumber {
            get {
                return ResourceManager.GetString("SIMCardSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SIMCardStatusNameEn {
            get {
                return ResourceManager.GetString("SIMCardStatusNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM Card.
        /// </summary>
        public static string SIMCardTitle {
            get {
                return ResourceManager.GetString("SIMCardTitle", resourceCulture);
            }
        }
    }
}
