//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Store {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Store() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Store", typeof(Store).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Delivery Date.
        /// </summary>
        public static string ActualDeliveryDate {
            get {
                return ResourceManager.GetString("ActualDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Delivery Time.
        /// </summary>
        public static string ActualDeliveryTime {
            get {
                return ResourceManager.GetString("ActualDeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery DateTime.
        /// </summary>
        public static string DeliveryDateTime {
            get {
                return ResourceManager.GetString("DeliveryDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Request.
        /// </summary>
        public static string DeliveryRequest {
            get {
                return ResourceManager.GetString("DeliveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Delivery Request.
        /// </summary>
        public static string DeliveryRequestAssign {
            get {
                return ResourceManager.GetString("DeliveryRequestAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Request Assign Successfully.
        /// </summary>
        public static string DeliveryRequestAssignSuccessMessage {
            get {
                return ResourceManager.GetString("DeliveryRequestAssignSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Delivery Request.
        /// </summary>
        public static string DeliveryRequestCreate {
            get {
                return ResourceManager.GetString("DeliveryRequestCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Request Details.
        /// </summary>
        public static string DeliveryRequestDetails {
            get {
                return ResourceManager.GetString("DeliveryRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Delivery Request.
        /// </summary>
        public static string DeliveryRequestEdit {
            get {
                return ResourceManager.GetString("DeliveryRequestEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Delivery Request.
        /// </summary>
        public static string DeliveryRequestNew {
            get {
                return ResourceManager.GetString("DeliveryRequestNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string DeliveryRequestNote {
            get {
                return ResourceManager.GetString("DeliveryRequestNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string DeliveryRequestStatus {
            get {
                return ResourceManager.GetString("DeliveryRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Time.
        /// </summary>
        public static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Device.
        /// </summary>
        public static string DeviceCreate {
            get {
                return ResourceManager.GetString("DeviceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string DeviceCreateDate {
            get {
                return ResourceManager.GetString("DeviceCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Details.
        /// </summary>
        public static string DeviceDetails {
            get {
                return ResourceManager.GetString("DeviceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Card.
        /// </summary>
        public static string DeviceEdit {
            get {
                return ResourceManager.GetString("DeviceEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI.
        /// </summary>
        public static string DeviceIMEI {
            get {
                return ResourceManager.GetString("DeviceIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type.
        /// </summary>
        public static string DeviceModelType {
            get {
                return ResourceManager.GetString("DeviceModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Device Model Type.
        /// </summary>
        public static string DeviceModelTypeCreate {
            get {
                return ResourceManager.GetString("DeviceModelTypeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Model Type Details.
        /// </summary>
        public static string DeviceModelTypeDetails {
            get {
                return ResourceManager.GetString("DeviceModelTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device Model Type.
        /// </summary>
        public static string DeviceModelTypeEdit {
            get {
                return ResourceManager.GetString("DeviceModelTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Model Type Id.
        /// </summary>
        public static string DeviceModelTypeId {
            get {
                return ResourceManager.GetString("DeviceModelTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Type.
        /// </summary>
        public static string DeviceModelTypeName {
            get {
                return ResourceManager.GetString("DeviceModelTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Model Type.
        /// </summary>
        public static string DeviceModelTypeNew {
            get {
                return ResourceManager.GetString("DeviceModelTypeNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Model Type.
        /// </summary>
        public static string DeviceModelTypeTitle {
            get {
                return ResourceManager.GetString("DeviceModelTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device.
        /// </summary>
        public static string DeviceNew {
            get {
                return ResourceManager.GetString("DeviceNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string DeviceSerialNumber {
            get {
                return ResourceManager.GetString("DeviceSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Status Details.
        /// </summary>
        public static string DeviceStatusDetails {
            get {
                return ResourceManager.GetString("DeviceStatusDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device Status.
        /// </summary>
        public static string DeviceStatusEdit {
            get {
                return ResourceManager.GetString("DeviceStatusEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status(Ar).
        /// </summary>
        public static string DeviceStatusNameAr {
            get {
                return ResourceManager.GetString("DeviceStatusNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DeviceStatusNameEn {
            get {
                return ResourceManager.GetString("DeviceStatusNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Status.
        /// </summary>
        public static string DeviceStatusTitle {
            get {
                return ResourceManager.GetString("DeviceStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string DeviceTitle {
            get {
                return ResourceManager.GetString("DeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware.
        /// </summary>
        public static string Firmware {
            get {
                return ResourceManager.GetString("Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string ItemFamily {
            get {
                return ResourceManager.GetString("ItemFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
    }
}
