//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Technician {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Technician() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Technician", typeof(Technician).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Request has been Approved.
        /// </summary>
        public static string ApprovedDeliveryRequestNotificationContent {
            get {
                return ResourceManager.GetString("ApprovedDeliveryRequestNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Delivery Request.
        /// </summary>
        public static string ApprovedDeliveryRequestNotificationTitle {
            get {
                return ResourceManager.GetString("ApprovedDeliveryRequestNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Approval.
        /// </summary>
        public static string ButtonDeliveryDeviceTechnicalApproval {
            get {
                return ResourceManager.GetString("ButtonDeliveryDeviceTechnicalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Approve.
        /// </summary>
        public static string DeliveryDeviceTechnicalApproval {
            get {
                return ResourceManager.GetString("DeliveryDeviceTechnicalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Note has been Technical Approved successfully.
        /// </summary>
        public static string DeliveryNoteTechnicalApprovedNotificationContent {
            get {
                return ResourceManager.GetString("DeliveryNoteTechnicalApprovedNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Note Technical Approved.
        /// </summary>
        public static string DeliveryNoteTechnicalApprovedNotificationTitle {
            get {
                return ResourceManager.GetString("DeliveryNoteTechnicalApprovedNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Technical Approval.
        /// </summary>
        public static string DeliveryTechnicalApproval {
            get {
                return ResourceManager.GetString("DeliveryTechnicalApproval", resourceCulture);
            }
        }
    }
}
