//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserService
    {
        public int UserServiceId { get; set; }
        public int UserId { get; set; }
        public int ServiceId { get; set; }
        public bool Active { get; set; }
        public int CreateUserId { get; set; }
        public int CreateDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
