//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AfaqyStoreEntities : DbContext
    {
        public AfaqyStoreEntities()
            : base("name=AfaqyStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<BrandServerPort> BrandServerPort { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<CustomerServerAccount> CustomerServerAccount { get; set; }
        public virtual DbSet<CustomerServerAccountStatusHistory> CustomerServerAccountStatusHistory { get; set; }
        public virtual DbSet<CustomerServerStatus> CustomerServerStatus { get; set; }
        public virtual DbSet<CustomerServerUser> CustomerServerUser { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DeviceModelType> DeviceModelType { get; set; }
        public virtual DbSet<DeviceServer> DeviceServer { get; set; }
        public virtual DbSet<DeviceSIM> DeviceSIM { get; set; }
        public virtual DbSet<DeviceStatus> DeviceStatus { get; set; }
        public virtual DbSet<DeviceStatusHistory> DeviceStatusHistory { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<ServerRole> ServerRole { get; set; }
        public virtual DbSet<ServerUnit> ServerUnit { get; set; }
        public virtual DbSet<ServerUserRole> ServerUserRole { get; set; }
        public virtual DbSet<SIMCard> SIMCard { get; set; }
        public virtual DbSet<SIMCardContract> SIMCardContract { get; set; }
        public virtual DbSet<SIMCardContractRenewal> SIMCardContractRenewal { get; set; }
        public virtual DbSet<SIMCardProvider> SIMCardProvider { get; set; }
        public virtual DbSet<SIMCardStatus> SIMCardStatus { get; set; }
        public virtual DbSet<SIMCardStatusHistory> SIMCardStatusHistory { get; set; }
        public virtual DbSet<SystemServerIP> SystemServerIP { get; set; }
        public virtual DbSet<TechniqueCompany> TechniqueCompany { get; set; }
        public virtual DbSet<TechniqueSystem> TechniqueSystem { get; set; }
        public virtual DbSet<TempDevice> TempDevice { get; set; }
        public virtual DbSet<BrandServerPortView> BrandServerPortView { get; set; }
        public virtual DbSet<CustomerServerAccountView> CustomerServerAccountView { get; set; }
        public virtual DbSet<CustomerServerUnitsCountView> CustomerServerUnitsCountView { get; set; }
        public virtual DbSet<CustomerServerUnitsView> CustomerServerUnitsView { get; set; }
        public virtual DbSet<CustomerView> CustomerView { get; set; }
        public virtual DbSet<DeviceSIMView> DeviceSIMView { get; set; }
        public virtual DbSet<DeviceView> DeviceView { get; set; }
        public virtual DbSet<SIMCardContractView> SIMCardContractView { get; set; }
        public virtual DbSet<SIMCardView> SIMCardView { get; set; }
        public virtual DbSet<SystemServerIPView> SystemServerIPView { get; set; }
        public virtual DbSet<UserView> UserView { get; set; }
    }
}
