//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerServerUnitsCountView
    {
        public string BranchName_en { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName_en { get; set; }
        public string CustomerName_ar { get; set; }
        public string ServerIP { get; set; }
        public int AccountId { get; set; }
        public string AccountUserName { get; set; }
        public string SeverCustomerName { get; set; }
        public Nullable<int> ClientStatus { get; set; }
        public Nullable<int> TotalUnitsCount { get; set; }
        public Nullable<int> WorkingUnitsCount { get; set; }
        public Nullable<int> DeletedUnitsCount { get; set; }
    }
}
