//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryNote()
        {
            this.DeliveryDetails = new HashSet<DeliveryDetails>();
        }
    
        public int DeliveryId { get; set; }
        public int POSId { get; set; }
        public int WarehouseId { get; set; }
        public int DeliveryRequestId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public int SaleTransactionTypeId { get; set; }
        public System.DateTime DeliveryDateTime { get; set; }
        public int DeliveryStatusId { get; set; }
        public string DolphinReference { get; set; }
        public Nullable<int> DolphinDeliveryId { get; set; }
        public int EmpoyeeId { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDetails> DeliveryDetails { get; set; }
        public virtual DeliveryRequest DeliveryRequest { get; set; }
        public virtual DeliveryStatus DeliveryStatus { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PointOfSale PointOfSale { get; set; }
        public virtual SaleTransactionType SaleTransactionType { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
