//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryRequest()
        {
            this.DeliveryNote = new HashSet<DeliveryNote>();
            this.DeliveryRequestDetails = new HashSet<DeliveryRequestDetails>();
            this.DeliveryRequestTechnician = new HashSet<DeliveryRequestTechnician>();
        }
    
        public int DeliveryRequestId { get; set; }
        public int cmp_seq { get; set; }
        public string POS_ps_code { get; set; }
        public string Warehouse_wa_code { get; set; }
        public int DeliveryRequestStatusId { get; set; }
        public int Customer_aux_id { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerContact_serial { get; set; }
        public string AlternativeContactName { get; set; }
        public string AlternativeContactTelephone { get; set; }
        public int SaleTransactionTypeId { get; set; }
        public System.DateTime DeliveryRequestDateTime { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDateTime { get; set; }
        public Nullable<int> SystemId { get; set; }
        public Nullable<bool> WithInstallationService { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryNote> DeliveryNote { get; set; }
        public virtual DeliveryRequestStatus DeliveryRequestStatus { get; set; }
        public virtual SaleTransactionType SaleTransactionType { get; set; }
        public virtual TechniqueSystem TechniqueSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryRequestDetails> DeliveryRequestDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryRequestTechnician> DeliveryRequestTechnician { get; set; }
    }
}
