//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDeviceView
    {
        public int DeliveryItemId { get; set; }
        public int DeliveryDetailsId { get; set; }
        public int DeliveryNoteId { get; set; }
        public int DeviceId { get; set; }
        public string SerialNumber { get; set; }
        public string IMEI { get; set; }
        public string Firmware { get; set; }
        public Nullable<int> Employee_aux_id { get; set; }
        public string name { get; set; }
        public string altname { get; set; }
        public Nullable<System.DateTime> InstallingDateTime { get; set; }
        public string CarPlateNum { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
        public string ia_name { get; set; }
        public string ia_shname { get; set; }
        public string ia_altname { get; set; }
        public string ia_shaltname { get; set; }
        public Nullable<decimal> ModelType_ia_item_id { get; set; }
        public int DeliveryDevice_cmp_seq { get; set; }
    }
}
