//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRequestView
    {
        public int DeliveryRequestId { get; set; }
        public string POS_ps_code { get; set; }
        public string ps_name { get; set; }
        public string ps_shname { get; set; }
        public string ps_altname { get; set; }
        public string ps_shaltname { get; set; }
        public int DeliveryRequestStatusId { get; set; }
        public string DeliveryRequestStatus_en { get; set; }
        public string DeliveryRequestStatus_ar { get; set; }
        public int Customer_aux_id { get; set; }
        public string name { get; set; }
        public string shortname { get; set; }
        public string altname { get; set; }
        public string shortaltname { get; set; }
        public int SaleTransactionTypeId { get; set; }
        public string SaleTransactionType_en { get; set; }
        public string SaleTransactionType_ar { get; set; }
        public string DeliveryRequestDateTime { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
        public int CreateUserId { get; set; }
        public string CreateUser_FirstName_en { get; set; }
        public string CreateUser_FirstName_ar { get; set; }
        public string CreateUser_LastName_en { get; set; }
        public string CreateUser_LastName_ar { get; set; }
        public string CreateUser_FullName_en { get; set; }
        public string CreateUser_FullName_ar { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public string ModifyUser_FirstName_en { get; set; }
        public string ModifyUser_FirstName_ar { get; set; }
        public string ModifyUser_LastName_en { get; set; }
        public string ModifyUser_LastName_ar { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser_FullName_en { get; set; }
        public string ModifyUser_FullName_ar { get; set; }
        public string Warehouse_wa_code { get; set; }
        public string wa_name { get; set; }
        public string wa_shname { get; set; }
        public string wa_altname { get; set; }
        public string wa_shaltname { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerContact_serial { get; set; }
        public string contact_name { get; set; }
        public string AlternativeContactName { get; set; }
        public string AlternativeContactTelephone { get; set; }
        public Nullable<int> SystemId { get; set; }
        public string SystemName { get; set; }
        public string ActualDeliveryDateTime { get; set; }
        public Nullable<bool> EditPermission { get; set; }
        public Nullable<bool> AssignPermission { get; set; }
        public Nullable<bool> StoreReceivedPermission { get; set; }
        public Nullable<bool> DeliveryPermission { get; set; }
        public Nullable<bool> WithInstallationService { get; set; }
    }
}
