//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDeviceView
    {
        public int DeliveryItemId { get; set; }
        public int DeliveryDetailsId { get; set; }
        public int DeliveryNoteId { get; set; }
        public int DeviceId { get; set; }
        public string SerialNumber { get; set; }
        public string IMEI { get; set; }
        public string Firmware { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string FirstName_en { get; set; }
        public string FirstName_ar { get; set; }
        public string LastName_en { get; set; }
        public string LastName_ar { get; set; }
        public Nullable<System.DateTime> InstallingDateTime { get; set; }
        public string CarPlateNum { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
        public string DeviceModelTypeName { get; set; }
        public Nullable<int> DeviceModelTypeId { get; set; }
    }
}
