//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRequestTechnicianView
    {
        public int DeliveryRequestTechnicalId { get; set; }
        public int DeliveryRequestId { get; set; }
        public int Employee_aux_id { get; set; }
        public string name { get; set; }
        public string altname { get; set; }
        public bool IsBlock { get; set; }
    }
}
