//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetailsView
    {
        public int DeliveryDetailsId { get; set; }
        public int DeliveryId { get; set; }
        public int DeviceModelTypeId { get; set; }
        public string DeviceModelTypeName { get; set; }
        public string ItemFamilyName_en { get; set; }
        public string ItemFamilyName_ar { get; set; }
        public int Quantity { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
    }
}
