//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public int EmployeeId { get; set; }
        public string FirstName_en { get; set; }
        public string FirstName_ar { get; set; }
        public string LastName_en { get; set; }
        public string LastName_ar { get; set; }
        public string Employee_FullName_en { get; set; }
        public string Employee_FullName_ar { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string ResidencyNumber { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string CountryName_en { get; set; }
        public string CountryName_ar { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string DepartmentName_en { get; set; }
        public string DepartmentName_ar { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string Manager_FirstName_en { get; set; }
        public string Manager_FirstName_ar { get; set; }
        public string Manager_LastName_en { get; set; }
        public string Manager_LastName_ar { get; set; }
        public string Branch_br_code { get; set; }
        public string br_name { get; set; }
        public string br_alt_name { get; set; }
        public string BranchShortName_en { get; set; }
        public string BranchShortAltName_ar { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsBlock { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreateUser_FirstName_en { get; set; }
        public string CreateUser_FirstName_ar { get; set; }
        public string CreateUser_LastName_en { get; set; }
        public string CreateUser_LastName_ar { get; set; }
        public string CreateUser_FullName_en { get; set; }
        public string CreateUser_FullName_ar { get; set; }
        public string ModifyUser_FirstName_en { get; set; }
        public string ModifyUser_FirstName_ar { get; set; }
        public string ModifyUser_LastName_en { get; set; }
        public string ModifyUser_LastName_ar { get; set; }
        public string ModifyUser_FullName_en { get; set; }
        public string ModifyUser_FullName_ar { get; set; }
    }
}
