//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fm_c_branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fm_c_branch()
        {
            this.im_points = new HashSet<im_points>();
            this.im_warehouse = new HashSet<im_warehouse>();
            this.it_trans_b = new HashSet<it_trans_b>();
        }
    
        public string br_code { get; set; }
        public int br_cmp_seq { get; set; }
        public string br_name { get; set; }
        public string br_sh_name { get; set; }
        public string br_alt_name { get; set; }
        public string br_sh_alt_name { get; set; }
        public string br_title { get; set; }
        public Nullable<int> br_closed { get; set; }
        public string br_adduser { get; set; }
        public Nullable<System.DateTime> br_adddate { get; set; }
        public string br_upduser { get; set; }
        public Nullable<System.DateTime> br_upddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<im_points> im_points { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<im_warehouse> im_warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_trans_b> it_trans_b { get; set; }
    }
}
