//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class im_family
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public im_family()
        {
            this.im_itema = new HashSet<im_itema>();
        }
    
        public int fa_cmp_seq { get; set; }
        public string fa_code { get; set; }
        public string fa_name { get; set; }
        public string fa_shname { get; set; }
        public string fa_altname { get; set; }
        public string fa_shaltname { get; set; }
        public string fa_adduser { get; set; }
        public Nullable<System.DateTime> fa_adddate { get; set; }
        public string fa_upduser { get; set; }
        public Nullable<System.DateTime> fa_upddate { get; set; }
        public Nullable<int> fa_famType { get; set; }
        public Nullable<int> fk_fa_cmp_seq { get; set; }
        public string fk_fa_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<im_itema> im_itema { get; set; }
    }
}
