//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class im_itemb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public im_itemb()
        {
            this.im_itema = new HashSet<im_itema>();
            this.im_itema1 = new HashSet<im_itema>();
            this.it_trans_b = new HashSet<it_trans_b>();
        }
    
        public decimal ib_serial_id { get; set; }
        public int ib_cmp_seq { get; set; }
        public decimal ib_ia_item_id { get; set; }
        public string ib_un_code { get; set; }
        public Nullable<decimal> ib_factor { get; set; }
        public string ib_barcode1 { get; set; }
        public Nullable<double> ib_weight_gross { get; set; }
        public Nullable<double> ib_weight_net { get; set; }
        public Nullable<double> ib_volume { get; set; }
        public string ib_def_bin_nb { get; set; }
        public string ib_def_wa_code { get; set; }
        public string ib_color { get; set; }
        public string ib_sup_ref { get; set; }
        public string ib_adduser { get; set; }
        public Nullable<System.DateTime> ib_adddate { get; set; }
        public string ib_upduser { get; set; }
        public Nullable<System.DateTime> ib_upddate { get; set; }
        public Nullable<int> ib_inactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<im_itema> im_itema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<im_itema> im_itema1 { get; set; }
        public virtual im_itema im_itema2 { get; set; }
        public virtual im_warehouse im_warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_trans_b> it_trans_b { get; set; }
    }
}
