//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class im_itema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public im_itema()
        {
            this.im_itemc = new HashSet<im_itemc>();
            this.im_itemb2 = new HashSet<im_itemb>();
        }
    
        public int ia_cmp_seq { get; set; }
        public decimal ia_item_id { get; set; }
        public string ia_item_code { get; set; }
        public string ia_name { get; set; }
        public string ia_shname { get; set; }
        public string ia_altname { get; set; }
        public string ia_shaltname { get; set; }
        public int ia_cura_seq { get; set; }
        public string ia_fa_code { get; set; }
        public Nullable<int> ia_cu_id { get; set; }
        public string ia_ty_code { get; set; }
        public Nullable<int> ia_br_id { get; set; }
        public string ia_uo_code { get; set; }
        public string ia_un_code { get; set; }
        public string ia_base_un_code { get; set; }
        public int ia_va_id { get; set; }
        public Nullable<int> ia_item_idle { get; set; }
        public Nullable<int> ia_item_blocked { get; set; }
        public Nullable<int> ia_use_expiry { get; set; }
        public Nullable<int> ia_use_size_color { get; set; }
        public Nullable<int> ia_use_dbl_qt { get; set; }
        public string ia_remark { get; set; }
        public Nullable<int> ia_aux_id { get; set; }
        public Nullable<int> ia_use_serial { get; set; }
        public Nullable<int> ia_consign { get; set; }
        public string ia_sku { get; set; }
        public Nullable<int> ia_service { get; set; }
        public Nullable<int> ia_use_kit { get; set; }
        public Nullable<int> ia_piece { get; set; }
        public string ia_picture { get; set; }
        public string ia_spec1 { get; set; }
        public string ia_spec2 { get; set; }
        public Nullable<decimal> ia_imItemid { get; set; }
        public Nullable<decimal> ia_prev3_price { get; set; }
        public Nullable<decimal> ia_prev2_price { get; set; }
        public Nullable<decimal> ia_prev1_price { get; set; }
        public Nullable<decimal> ia_def_price { get; set; }
        public Nullable<double> ia_profit_Margin { get; set; }
        public Nullable<int> ia_export_eshop { get; set; }
        public string ia_UsrFld1 { get; set; }
        public string ia_UsrFld2 { get; set; }
        public string ia_UsrFld3 { get; set; }
        public string ia_UsrFld4 { get; set; }
        public string ia_UsrFld5 { get; set; }
        public string ia_UsrFld6 { get; set; }
        public Nullable<decimal> ia_ib_base_id { get; set; }
        public Nullable<decimal> ia_ib_s_id { get; set; }
        public string ia_sc_code { get; set; }
        public int ia_use_size { get; set; }
        public int ia_autofill { get; set; }
        public Nullable<int> ia_sell_cura_seq { get; set; }
        public Nullable<System.DateTime> ia_creat_date { get; set; }
        public Nullable<double> ia_royalty_perc { get; set; }
        public Nullable<int> ia_status { get; set; }
        public string ia_sz_or_szcl { get; set; }
        public Nullable<int> ia_sca_id { get; set; }
        public Nullable<decimal> ia_ReorderLevel { get; set; }
        public Nullable<decimal> ia_MinStkHolding { get; set; }
        public Nullable<decimal> ia_LeadTime { get; set; }
        public string ia_royalty_netgross { get; set; }
        public decimal ia_convfactor { get; set; }
        public int ia_BarcodeWeight { get; set; }
        public string ia_adduser { get; set; }
        public Nullable<System.DateTime> ia_adddate { get; set; }
        public string ia_upduser { get; set; }
        public Nullable<System.DateTime> ia_upddate { get; set; }
        public Nullable<int> ia_division_id { get; set; }
        public Nullable<int> ia_season_id { get; set; }
        public Nullable<int> ia_year { get; set; }
        public int ia_type { get; set; }
        public Nullable<double> ia_max_disc { get; set; }
        public Nullable<int> fk_eq_seq { get; set; }
        public Nullable<decimal> ia_minstk { get; set; }
        public Nullable<decimal> ia_maxstk { get; set; }
        public int ia_openitem { get; set; }
        public Nullable<int> ia_expirycheck { get; set; }
        public Nullable<int> ia_wterms1 { get; set; }
        public Nullable<int> ia_wterms2 { get; set; }
        public Nullable<int> ia_wtermson { get; set; }
        public Nullable<int> ia_usedqty { get; set; }
        public Nullable<int> ia_barcode { get; set; }
        public Nullable<decimal> ia_s_minqty { get; set; }
        public string ia_formula { get; set; }
        public Nullable<decimal> ia_directcomm { get; set; }
        public Nullable<int> ia_mandatorySerial { get; set; }
        public Nullable<int> ia_securedSerial { get; set; }
        public Nullable<int> ia_serialUsedForGiftCard { get; set; }
        public Nullable<decimal> ia_width { get; set; }
        public Nullable<decimal> ia_thickness { get; set; }
        public Nullable<decimal> ia_weight { get; set; }
        public Nullable<decimal> ia_height { get; set; }
        public Nullable<decimal> ia_volume { get; set; }
        public Nullable<decimal> ia_nbrOfSheet { get; set; }
        public Nullable<decimal> ia_priceConvfactor { get; set; }
        public Nullable<int> ia_formulaUsedFor { get; set; }
        public string ia_itemFormulaUnit { get; set; }
        public Nullable<int> ia_goldItem { get; set; }
        public string ia_UsrFld7 { get; set; }
        public string ia_UsrFld7Rich { get; set; }
        public string ia_UsrFld8 { get; set; }
        public string ia_UsrFld8Rich { get; set; }
        public Nullable<decimal> fk_ia_item_id_grp { get; set; }
        public Nullable<int> ia_bulkserial { get; set; }
        public Nullable<decimal> ia_tax { get; set; }
        public Nullable<int> ia_splititemqty { get; set; }
        public Nullable<int> ia_PromoGiftcard { get; set; }
    
        public virtual im_itemb im_itemb { get; set; }
        public virtual im_itemb im_itemb1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<im_itemc> im_itemc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<im_itemb> im_itemb2 { get; set; }
        public virtual im_family im_family { get; set; }
    }
}
