//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class im_points
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public im_points()
        {
            this.it_trans_a = new HashSet<it_trans_a>();
        }
    
        public int ps_cmp_seq { get; set; }
        public string ps_code { get; set; }
        public string ps_name { get; set; }
        public string ps_shname { get; set; }
        public string ps_altname { get; set; }
        public string ps_shaltname { get; set; }
        public string ps_branch { get; set; }
        public Nullable<int> ps_Acc_cmp_seq { get; set; }
    
        public virtual fm_c_branch fm_c_branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_trans_a> it_trans_a { get; set; }
    }
}
