//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class im_warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public im_warehouse()
        {
            this.im_itemb = new HashSet<im_itemb>();
            this.im_itemc = new HashSet<im_itemc>();
            this.it_trans_a = new HashSet<it_trans_a>();
            this.it_trans_a1 = new HashSet<it_trans_a>();
            this.it_trans_a2 = new HashSet<it_trans_a>();
            this.it_trans_b = new HashSet<it_trans_b>();
            this.it_trans_b1 = new HashSet<it_trans_b>();
            this.it_trans_b2 = new HashSet<it_trans_b>();
        }
    
        public int wa_cmp_seq { get; set; }
        public string wa_code { get; set; }
        public string wa_name { get; set; }
        public string wa_shname { get; set; }
        public string wa_altname { get; set; }
        public string wa_shaltname { get; set; }
        public string wa_costcenter { get; set; }
        public Nullable<int> wa_Acc_cmp_seq { get; set; }
        public string wa_adduser { get; set; }
        public Nullable<System.DateTime> wa_adddate { get; set; }
        public string wa_upduser { get; set; }
        public Nullable<System.DateTime> wa_upddate { get; set; }
        public Nullable<int> wa_consign { get; set; }
        public Nullable<int> wa_Grp { get; set; }
        public Nullable<int> fk_wg_seq { get; set; }
        public Nullable<int> wa_inactive { get; set; }
    
        public virtual fm_c_branch fm_c_branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<im_itemb> im_itemb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<im_itemc> im_itemc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_trans_a> it_trans_a { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_trans_a> it_trans_a1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_trans_a> it_trans_a2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_trans_b> it_trans_b { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_trans_b> it_trans_b1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<it_trans_b> it_trans_b2 { get; set; }
    }
}
