//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_trans_b
    {
        public decimal trb_serial_id { get; set; }
        public int trb_cmp_seq { get; set; }
        public decimal trb_tra_ref_id { get; set; }
        public int trb_tra_ref_type { get; set; }
        public decimal trb_ia_item_id { get; set; }
        public Nullable<decimal> trb_ib_serial_id { get; set; }
        public Nullable<decimal> trb_ic_serial_id { get; set; }
        public Nullable<int> trb_re_id { get; set; }
        public string trb_wa_code { get; set; }
        public string trb_ps_code { get; set; }
        public string trb_color { get; set; }
        public string trb_un_code { get; set; }
        public Nullable<decimal> trb_f_qt { get; set; }
        public string trb_s_un_code { get; set; }
        public Nullable<decimal> trb_s_qt { get; set; }
        public Nullable<decimal> trb_s_f_qt { get; set; }
        public Nullable<double> trb_price { get; set; }
        public Nullable<decimal> trb_tra_refto_id { get; set; }
        public Nullable<int> trb_tra_refto_type { get; set; }
        public Nullable<double> trb_vat { get; set; }
        public Nullable<int> trb_sign { get; set; }
        public Nullable<double> trb_cost { get; set; }
        public Nullable<double> trb_disc { get; set; }
        public Nullable<double> trb_price_fl { get; set; }
        public Nullable<double> trb_price_sl { get; set; }
        public Nullable<double> trb_total { get; set; }
        public Nullable<double> trb_dbl_qt { get; set; }
        public Nullable<int> trb_cura_seq { get; set; }
        public Nullable<double> trb_avg_cost_for { get; set; }
        public Nullable<double> trb_avg_cost_fl { get; set; }
        public Nullable<double> trb_avg_cost_sl { get; set; }
        public string trb_desc { get; set; }
        public Nullable<double> trb_custom_pct { get; set; }
        public Nullable<decimal> trb_refto_serial_id { get; set; }
        public Nullable<double> trb_qty_hand { get; set; }
        public Nullable<decimal> trb_qty1 { get; set; }
        public Nullable<decimal> trb_affect_qty1 { get; set; }
        public Nullable<decimal> trb_deliv_f_qt { get; set; }
        public Nullable<decimal> trb_deliv_qty1 { get; set; }
        public Nullable<decimal> trb_line_serialnumber { get; set; }
        public string trb_kit_item { get; set; }
        public Nullable<int> trb_parent { get; set; }
        public string trb_branch_cost { get; set; }
        public string trb_branch { get; set; }
        public string trb_costcenter { get; set; }
        public string trb_albaran { get; set; }
        public string trb_box_no { get; set; }
        public Nullable<double> trb_cost_rate { get; set; }
        public Nullable<int> trb_lot_qty { get; set; }
        public Nullable<float> trb_selling { get; set; }
        public Nullable<decimal> trb_remaining_qty { get; set; }
        public Nullable<int> trb_acc_cmp_seq { get; set; }
        public Nullable<int> trb_ia_status { get; set; }
        public Nullable<double> trb_costnew { get; set; }
        public Nullable<int> trb_prodt_id { get; set; }
        public Nullable<double> trb_f_vat { get; set; }
        public Nullable<System.DateTime> trb_delivdate { get; set; }
        public Nullable<int> trb_trf_flag { get; set; }
        public string trb_uombase { get; set; }
        public Nullable<decimal> trb_qtybase { get; set; }
        public Nullable<int> trb_sclink_id { get; set; }
        public Nullable<double> trb_pricettc { get; set; }
        public string trb_pc_code { get; set; }
        public int trb_withttc { get; set; }
        public Nullable<double> trb_labor { get; set; }
        public Nullable<int> trb_active { get; set; }
        public Nullable<decimal> trb_book_qty { get; set; }
        public Nullable<decimal> fk_ik_item_id { get; set; }
        public Nullable<double> trb_replcmnt_cost { get; set; }
        public Nullable<decimal> fk_ia_item_id_lab { get; set; }
        public Nullable<int> fk_cura_seq_lab { get; set; }
        public string trb_kit_desc { get; set; }
        public Nullable<decimal> trb_vat_pct { get; set; }
        public Nullable<System.DateTime> trb_wmaturity { get; set; }
        public Nullable<decimal> trb_width { get; set; }
        public Nullable<decimal> trb_height { get; set; }
        public Nullable<decimal> trb_thickness { get; set; }
        public Nullable<decimal> trb_volume { get; set; }
        public Nullable<decimal> trb_fwidth { get; set; }
        public Nullable<decimal> trb_fheight { get; set; }
        public Nullable<decimal> trb_fthickness { get; set; }
        public Nullable<decimal> trb_fvolume { get; set; }
        public Nullable<decimal> trb_weight { get; set; }
        public Nullable<decimal> trb_fweight { get; set; }
        public Nullable<decimal> trb_nbsheets { get; set; }
        public Nullable<decimal> trb_fnbsheets { get; set; }
        public Nullable<int> fk_as_cmp_seq { get; set; }
        public Nullable<decimal> fk_as_trb_serial_id { get; set; }
        public Nullable<int> fk_as_serial { get; set; }
        public string fk_trb_shipment { get; set; }
        public Nullable<double> trb_cost1st { get; set; }
        public Nullable<double> trb_cost2nd { get; set; }
        public Nullable<int> fk_jc_cmp_seq { get; set; }
        public Nullable<decimal> fk_jba_code { get; set; }
        public Nullable<int> fk_jbb_seq { get; set; }
        public Nullable<decimal> trb_directcomm { get; set; }
        public Nullable<double> trb_price_formula { get; set; }
        public string trb_truck { get; set; }
        public Nullable<System.DateTime> trb_deliv_date { get; set; }
        public string trb_DelRemark { get; set; }
        public Nullable<int> trb_promoted { get; set; }
        public string trb_wa_code_to { get; set; }
        public string trb_wa_code_from { get; set; }
        public Nullable<decimal> trb_receiv_qty1 { get; set; }
        public Nullable<decimal> trb_receiv_f_qt { get; set; }
    
        public virtual fm_c_branch fm_c_branch { get; set; }
        public virtual im_itemb im_itemb { get; set; }
        public virtual im_itemc im_itemc { get; set; }
        public virtual im_warehouse im_warehouse { get; set; }
        public virtual im_warehouse im_warehouse1 { get; set; }
        public virtual im_warehouse im_warehouse2 { get; set; }
        public virtual it_trans_a it_trans_a { get; set; }
    }
}
