//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_trans_serial
    {
        public decimal trs_trb_line_serialnumber { get; set; }
        public int trs_cmp_seq { get; set; }
        public int trs_tra_ref_type { get; set; }
        public decimal trs_tra_ref_id { get; set; }
        public Nullable<decimal> trs_ia_item_id { get; set; }
        public string trs_is_serialnumber { get; set; }
        public Nullable<int> trs_tra_aux_id { get; set; }
        public Nullable<System.DateTime> trs_tra_date { get; set; }
        public Nullable<System.DateTime> trs_wmaturity { get; set; }
    }
}
