//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationContent { get; set; }
        public string StyleClass { get; set; }
        public string NotificationType { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> NotificationTypeId { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string ReferenceLink { get; set; }
    
        public virtual NotificationType NotificationType1 { get; set; }
    }
}
