//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rpaux
    {
        public int aux_id { get; set; }
        public string name { get; set; }
        public string shortname { get; set; }
        public string altname { get; set; }
        public string shortaltname { get; set; }
        public string email { get; set; }
        public string building { get; set; }
        public string street { get; set; }
        public string pobox { get; set; }
        public string remark { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public Nullable<int> ap { get; set; }
        public Nullable<int> ar { get; set; }
        public int act_id { get; set; }
        public Nullable<int> due_days { get; set; }
        public Nullable<int> other_ap { get; set; }
        public Nullable<int> other_ar { get; set; }
        public Nullable<int> employee { get; set; }
        public Nullable<int> salecode { get; set; }
        public Nullable<int> cur_seq { get; set; }
        public string adduser { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string upduser { get; set; }
        public Nullable<System.DateTime> upddate { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string cardid { get; set; }
        public Nullable<int> aux_gr_id { get; set; }
        public Nullable<int> aux_blocked { get; set; }
        public int aux_type { get; set; }
        public string aux_first_name { get; set; }
        public string aux_middle_name { get; set; }
        public string aux_last_name { get; set; }
        public Nullable<int> fk_tl_seq { get; set; }
        public string aux_gender { get; set; }
        public Nullable<int> fk_rp_serial { get; set; }
        public string aux_website { get; set; }
        public string aux_taxnumb { get; set; }
        public int aux_localforeign { get; set; }
        public Nullable<int> aux_Status { get; set; }
        public string fk_vdus_code { get; set; }
        public Nullable<int> fk_TaxCat_Seq { get; set; }
        public string aux_GMAddress { get; set; }
        public string aux_GMLat { get; set; }
        public string aux_GMLong { get; set; }
    
        public virtual rpauxname rpauxname { get; set; }
    }
}
