//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RpauxEmployeeView
    {
        public int aux_id { get; set; }
        public string name { get; set; }
        public string altname { get; set; }
        public string country { get; set; }
        public string co_name { get; set; }
        public string co_shname { get; set; }
        public string co_altname { get; set; }
        public string co_shaltname { get; set; }
        public Nullable<int> aux_blocked { get; set; }
    }
}
