//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerUserRole
    {
        public int ServerUserRoleId { get; set; }
        public int CustomerServerUserId { get; set; }
        public int ServerRoleId { get; set; }
        public bool IsBlock { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual CustomerServerUser CustomerServerUser { get; set; }
        public virtual ServerRole ServerRole { get; set; }
    }
}
