//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerUnit
    {
        public int UnitId { get; set; }
        public string GSMNumber { get; set; }
        public string SIMSerial { get; set; }
        public string DeviceIMEI { get; set; }
        public string DeviceSerial { get; set; }
        public Nullable<int> DeviceStatus { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeviceServerName { get; set; }
        public Nullable<System.DateTime> LastConnection { get; set; }
        public string ServerIP { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> ClientStatus { get; set; }
        public bool IsCorrect { get; set; }
    }
}
