//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMCardStatusHistory
    {
        public int HistoryId { get; set; }
        public int SIMCardId { get; set; }
        public int SIMCardStatusId { get; set; }
        public string Warehouse_wa_code { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual SIMCardStatus SIMCardStatus { get; set; }
    }
}
