//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMCardContractRenewal
    {
        public int ContractRenewalId { get; set; }
        public int ContractId { get; set; }
        public System.DateTime RenewalDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public decimal ItemCost { get; set; }
        public int CurrencyId { get; set; }
        public bool IsBlock { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual SIMCardContract SIMCardContract { get; set; }
    }
}
