//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIMCard()
        {
            this.DeviceSIM = new HashSet<DeviceSIM>();
            this.SIMCardStatusHistory = new HashSet<SIMCardStatusHistory>();
        }
    
        public int SIMCardId { get; set; }
        public string SerialNumber { get; set; }
        public string CompanySerialNumber { get; set; }
        public string GSM { get; set; }
        public int SIMCardStatusId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IsBlock { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceSIM> DeviceSIM { get; set; }
        public virtual SIMCardContract SIMCardContract { get; set; }
        public virtual SIMCardStatus SIMCardStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SIMCardStatusHistory> SIMCardStatusHistory { get; set; }
    }
}
