//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMCardView
    {
        public int SIMCardId { get; set; }
        public string Warehouse_wa_code { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseShortName { get; set; }
        public string WarehouseName_en { get; set; }
        public string WarehouseShortName_en { get; set; }
        public string ProviderName_en { get; set; }
        public string ProviderName_ar { get; set; }
        public string ContractNo { get; set; }
        public string CompanySerialNumber { get; set; }
        public string SerialNumber { get; set; }
        public string GSM { get; set; }
        public string AlternativeGSM { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public decimal Cost { get; set; }
        public string CurrencyName_en { get; set; }
        public string CurrencyName_ar { get; set; }
        public string SIMCardStatusName_en { get; set; }
        public string SIMCardStatusName_ar { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
        public string CreateUser_FirstName_en { get; set; }
        public string CreateUser_FirstName_ar { get; set; }
        public string CreateUser_LastName_en { get; set; }
        public string CreateUser_LastName_ar { get; set; }
        public string CreateUser_FullName_en { get; set; }
        public string CreateUser_FullName_ar { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyUser_FirstName_en { get; set; }
        public string ModifyUser_FirstName_ar { get; set; }
        public string ModifyUser_LastName_en { get; set; }
        public string ModifyUser_LastName_ar { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser_FullName_en { get; set; }
        public string ModifyUser_FullName_ar { get; set; }
    }
}
