//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionDetails()
        {
            this.TransactionDetails1 = new HashSet<TransactionDetails>();
            this.TransactionItem = new HashSet<TransactionItem>();
        }
    
        public int TransactionDetailsId { get; set; }
        public int cmp_seq { get; set; }
        public int TransactionId { get; set; }
        public decimal ModelType_ia_item_id { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> DolphinTransB_trb_serial_id { get; set; }
        public Nullable<int> ReferenceTransactionDetailsId { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Transaction Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetails> TransactionDetails1 { get; set; }
        public virtual TransactionDetails TransactionDetails2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionItem> TransactionItem { get; set; }
    }
}
