//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionItem()
        {
            this.TransactionItemInfoHistory = new HashSet<TransactionItemInfoHistory>();
        }
    
        public int TransactionItemId { get; set; }
        public int cmp_seq { get; set; }
        public int TransactionDetailsId { get; set; }
        public Nullable<decimal> ModelType_ia_item_id { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<int> Employee_aux_id { get; set; }
        public Nullable<System.DateTime> InstallingDateTime { get; set; }
        public string DeviceNaming_en { get; set; }
        public string DeviceNaming_ar { get; set; }
        public Nullable<int> DeviceNamingTypeId { get; set; }
        public Nullable<bool> AddToServer { get; set; }
        public Nullable<bool> TrackWithTechnician { get; set; }
        public Nullable<bool> ServerUpdated { get; set; }
        public Nullable<bool> TechnicalApproval { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public string Note { get; set; }
        public bool IsBlock { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionItemInfoHistory> TransactionItemInfoHistory { get; set; }
        public virtual TransactionDetails TransactionDetails { get; set; }
    }
}
