//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afaqy_Store.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName_en { get; set; }
        public string FirstName_ar { get; set; }
        public string LastName_en { get; set; }
        public string LastName_ar { get; set; }
        public string User_FullName_en { get; set; }
        public string User_FullName_ar { get; set; }
    }
}
